### ISSUE TITLE
Internal transaction fetcher duplicate entry

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#262]
I am receiving this error over and over.
```
[error] Task #PID<0.1924.0> started from Explorer.Indexer.InternalTransactionFetcher terminating
** (Postgrex.Error) ERROR 23505 (unique_violation): duplicate key value violates unique constraint "internal_transactions_transaction_hash_index_index"

    table: internal_transactions
    constraint: internal_transactions_transaction_hash_index_index

Key (transaction_hash, index)=(\xe8402d648f490a2a6527ca91c9c1154705974f3138d272dc8d864fbad00d43df, 0) already exists.
    (ecto) lib/ecto/adapters/sql.ex:200: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:85: Ecto.Adapters.Postgres.insert_all/7
    (ecto) lib/ecto/repo/schema.ex:52: Ecto.Repo.Schema.do_insert_all/7
    (explorer) lib/explorer/repo.ex:24: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain.ex:1894: Explorer.Chain.insert_changes_list/2
    (explorer) lib/explorer/chain.ex:1849: Explorer.Chain.insert_internal_transactions/2
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/indexer/internal_transaction_fetcher.ex:76: Explorer.Indexer.InternalTransactionFetcher.run/2
    (explorer) lib/explorer/buffered_task.ex:328: anonymous fn/3 in Explorer.BufferedTask.spawn_next_batch/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<3.48319259/0 in Explorer.BufferedTask.spawn_next_batch/1>
    Args: []```

**Comment by acravenho** [comment]
Duplicate of #270
