### ISSUE TITLE
Pending transaction indexer terminating

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#267]
On `core` chain I'm receiving this error message every second:

```[error] Task #PID<0.23845.9> started from Explorer.Indexer.PendingTransactionFetcher terminating
** (MatchError) no match of right hand side value: {:error, %{"code" => -32601, "message" => "Method not found"}}
    (explorer) lib/explorer/indexer/pending_transaction_fetcher.ex:89: Explorer.Indexer.PendingTransactionFetcher.task/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<2.49615225/0 in Explorer.Indexer.PendingTransactionFetcher.handle_info/2>
    Args: []
[error] pending transaction fetcher task exited due to {{:badmatch, {:error, %{"code" => -32601, "message" => "Method not found"}}}, [{Explorer.Indexer.PendingTransactionFetcher, :task, 1, [file: 'lib/explorer/indexer/pending_transaction_fetcher.ex', line: 89]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 88]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}.  Rescheduling.
```
I didn't see this message on `sokol`.

**Comment by KronicDeth** [comment]
That would seem to imply that `parity_pendingTransactions` is not supported on the nodes you're talking to.  Maybe those methods aren't enabled in the JSONRPC?  In Geth you have to turn on each namespace.  Is it the same for Parity?

**Comment by KronicDeth** [comment]
@acravenho did you resolve this with @poanetwork/devops-team since it works for Sokol?

**Comment by acravenho** [comment]
@KronicDeth Yes, this has been resolved.
