### ISSUE TITLE
Duplicate changes are being sent through `insert_internal_transactions`

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/poa-explorer#289]
With the improved logging from #285, I was able to get a changes list that triggers the `ON CONFLICT DO UPDATE command cannot affect row a second time` error.

<details>

```
[error] Task #PID<0.1537.4> started from Explorer.Indexer.InternalTransactionFetcher terminating
** (Postgrex.Error) ERROR 21000 (cardinality_violation): ON CONFLICT DO UPDATE command cannot affect row a second time
    (explorer) lib/explorer/repo.ex:54: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain.ex:2067: Explorer.Chain.insert_changes_list/2
    (explorer) lib/explorer/chain.ex:2020: Explorer.Chain.insert_internal_transactions/2
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/indexer/internal_transaction_fetcher.ex:76: Explorer.Indexer.InternalTransactionFetcher.run/2
    (explorer) lib/explorer/buffered_task.ex:328: anonymous fn/3 in Explorer.BufferedTask.spawn_next_batch/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<3.48319259/0 in Explorer.BufferedTask.spawn_next_batch/1>
    Args: []
[error] Could not insert all of chunk into Elixir.Explorer.Chain.InternalTransaction using options because of error.

Chunk:

[
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<190, 170, 52, 8, 74, 184, 81, 213, 69, 230, 159, 229, 75, 178, 81, 131, 36, 36, 223, 203>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 53, 76, 4, 144, 90, 67, 94, 114, 56, 184, 150, 133, 178, 199, 147, 104, 165, 216, 203>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<3, 205, 88, 153, 166, 59, 111, 98, 34, 175, 218, 135, 5, 208, 89, 253, 90, 125, 18, 107, 202, 190, 150, 47, 182, 84, 217, 115, 110, 107, 202, 250>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>}, 
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<190, 170, 52, 8, 74, 184, 81, 213, 69, 230, 159, 229, 75, 178, 81, 131, 36, 36, 223, 203>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 53, 76, 4, 144, 90, 67, 94, 114, 56, 184, 150, 133, 178, 199, 147, 104, 165, 216, 203>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<3, 205, 88, 153, 166, 59, 111, 98, 34, 175, 218, 135, 5, 208, 89, 253, 90, 125, 18, 107, 202, 190, 150, 47, 182, 84, 217, 115, 110, 107, 202, 250>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>}, 
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<63, 244, 171, 210, 239, 193, 176, 206, 195, 225, 134, 16, 25, 15, 217, 131, 14, 211, 252, 209>>}, gas: #Decimal<919000>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<195, 102, 66, 153, 103, 37, 31, 139, 13, 255, 232, 173, 233, 98, 1, 209, 63, 157, 13, 227>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<27, 254, 176, 85, 138, 230, 50, 49, 60, 215, 252, 178, 194, 5, 112, 238, 69, 70, 82, 211, 248, 230, 9, 111, 6, 87, 65, 178, 67, 229, 96, 210>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>}, 
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<190, 170, 52, 8, 74, 184, 81, 213, 69, 230, 159, 229, 75, 178, 81, 131, 36, 36, 223, 203>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 53, 76, 4, 144, 90, 67, 94, 114, 56, 184, 150, 133, 178, 199, 147, 104, 165, 216, 203>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<49, 62, 61, 165, 170, 66, 172, 160, 34, 32, 75, 36, 142, 17, 161, 72, 189, 173, 238, 180, 218, 90, 201, 12, 134, 102, 73, 130, 10, 83, 63, 41>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>}, 
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<63, 244, 171, 210, 239, 193, 176, 206, 195, 225, 134, 16, 25, 15, 217, 131, 14, 211, 252, 209>>}, gas: #Decimal<919000>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<195, 102, 66, 153, 103, 37, 31, 139, 13, 255, 232, 173, 233, 98, 1, 209, 63, 157, 13, 227>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<78, 53, 147, 51, 128, 104, 203, 35, 43, 73, 141, 121, 120, 164, 150, 181, 40, 180, 64, 156, 88, 105, 50, 27, 142, 202, 151, 59, 7, 209, 231, 94>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>}, 
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<190, 170, 52, 8, 74, 184, 81, 213, 69, 230, 159, 229, 75, 178, 81, 131, 36, 36, 223, 203>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 53, 76, 4, 144, 90, 67, 94, 114, 56, 184, 150, 133, 178, 199, 147, 104, 165, 216, 203>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<85, 83, 0, 175, 111, 209, 54, 88, 222, 78, 155, 192, 175, 190, 48, 84, 122, 196, 229, 178, 112, 146, 102, 1, 118, 77, 94, 176, 176, 203, 78, 157>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>}, 
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<63, 244, 171, 210, 239, 193, 176, 206, 195, 225, 134, 16, 25, 15, 217, 131, 14, 211, 252, 209>>}, gas: #Decimal<919000>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<195, 102, 66, 153, 103, 37, 31, 139, 13, 255, 232, 173, 233, 98, 1, 209, 63, 157, 13, 227>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<156, 22, 136, 119, 191, 132, 129, 26, 77, 169, 128, 153, 186, 68, 56, 47, 173, 80, 23, 104, 70, 77, 166, 88, 188, 140, 80, 4, 198, 57, 171, ...>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>}, 
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<190, 170, 52, 8, 74, 184, 81, 213, 69, 230, 159, 229, 75, 178, 81, 131, 36, 36, 223, 203>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 53, 76, 4, 144, 90, 67, 94, 114, 56, 184, 150, 133, 178, 199, 147, 104, 165, 216, 203>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<182, 148, 255, 197, 242, 39, 17, 11, 193, 153, 30, 214, 84, 66, 173, 58, 70, 247, 100, 154, 65, 153, 129, 42, 67, 194, 75, 54, 158, 69, ...>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>}, 
%{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<63, 244, 171, 210, 239, 193, 176, 206, 195, 225, 134, 16, 25, 15, 217, 131, 14, 211, 252, 209>>}, gas: #Decimal<919000>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<195, 102, 66, 153, 103, 37, 31, 139, 13, 255, 232, 173, 233, 98, 1, 209, 63, 157, 13, 227>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<211, 244, 89, 138, 182, 226, 236, 11, 178, 9, 2, 143, 214, 52, 85, 91, 210, 94, 46, 245, 8, 105, 111, 59, 177, 207, 235, 244, 57, ...>>}, type: :call, updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, value: #Explorer.Chain.Wei<20000000000>},
 %{call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<63, 244, 171, 210, 239, 193, 176, 206, 195, 225, 134, 16, 25, 15, 217, 131, 14, 211, 252, 209>>}, gas: #Decimal<919000>, gas_used: #Decimal<0>, index: 0, inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<195, 102, 66, 153, 103, 37, 31, 139, 13, 255, 232, 173, 233, 98, 1, 209, 63, 157, 13, 227>>}, trace_address: [], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<240, 71, 22 (truncated)
```

</details>

It appears to happen with the first two entries, that both are

```elixir
%{
  call_type: :call, 
  from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<190, 170, 52, 8, 74, 184, 81, 213, 69, 230, 159, 229, 75, 178, 81, 131, 36, 36, 223, 203>>}, 
  gas: #Decimal<0>, 
  gas_used: #Decimal<0>, 
  index: 0,
  inserted_at: #DateTime<2018-06-14 14:33:12.878345Z>, 
  output: %Explorer.Chain.Data{bytes: ""}, 
  to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 53, 76, 4, 144, 90, 67, 94, 114, 56, 184, 150, 133, 178, 199, 147, 104, 165, 216, 203>>}, 
  trace_address: [], 
  transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<3, 205, 88, 153, 166, 59, 111, 98, 34, 175, 218, 135, 5, 208, 89, 253, 90, 125, 18, 107, 202, 190, 150, 47, 182, 84, 217, 115, 110, 107, 202, 250>>}, 
  type: :call, 
  updated_at: #DateTime<2018-06-14 14:33:12.878345Z>, 
  value: #Explorer.Chain.Wei<20000000000>
}
```

`%Explorer.Chain.Hash{byte_count: 32, bytes: <<3, 205, 88, 153, 166, 59, 111, 98, 34, 175, 218, 135, 5, 208, 89, 253, 90, 125, 18, 107, 202, 190, 150, 47, 182, 84, 217, 115, 110, 107, 202, 250>>}` converted back to a string is `0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa`.

Using `curl`:

```sh
curl --data '{"method":"trace_replayTransaction","params":["0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa", ["trace"]],"id":1,"jsonrpc":"2.0"}' \
  -H "Content-Type: application/json" \
  -X POST "https://sokol-trace.poa.network"
```

the response is

```
{
  "jsonrpc": "2.0",
  "result": {
    "output": "0x",
    "stateDiff": null,
    "trace": [
      {
        "action": {
          "callType": "call",
          "from": "0xbeaa34084ab851d545e69fe54bb251832424dfcb",
          "gas": "0x0",
          "input": "0x",
          "to": "0xe3354c04905a435e7238b89685b2c79368a5d8cb",
          "value": "0x4a817c800"
        },
        "result": {
          "gasUsed": "0x0",
          "output": "0x"
        },
        "subtraces": 0,
        "traceAddress": [
          
        ],
        "type": "call"
      }
    ],
    "vmTrace": null
  },
  "id": 1
}
```

So, there should only be 1 internal transaction overall for `0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa`.

**Comment by KronicDeth** [comment]
Using the following test:


```elixir
defmodule Explorer.Indexer.InternalTransactionFetcherTest do
  use Explorer.DataCase, async: false

  alias Explorer.Chain.Transaction
  alias Explorer.Indexer.{AddressBalanceFetcherCase, InternalTransactionFetcher}
  
  describe "run/2" do
    test "dupes" do
      start_supervised!({Task.Supervisor, name: Explorer.Indexer.TaskSupervisor})
      AddressBalanceFetcherCase.start_supervised!()

      insert(:transaction, hash: "0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa")
      assert InternalTransactionFetcher.run(["0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa"], 0) == :ok
    end
  end
end
```

I determined `InternalTransactionFetcher.run/2` with  `0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa` runs correctly, so `EthereumJSONRPC.fetch_internal_transactions` is not outputting duplicates.  Something must be buffering multiple copies of `0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa`.

**Comment by KronicDeth** [comment]
```
test "dupes" do
      start_supervised!({Task.Supervisor, name: Explorer.Indexer.TaskSupervisor})
      AddressBalanceFetcherCase.start_supervised!()

      insert(:transaction, hash: "0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa")
      assert InternalTransactionFetcher.run(["0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa", "0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa"], 0) == :ok
    end
```

does reproduce the bug, so a duplicate passed to `run` is proximal cause in `InternalTransactionFetcher`.

**Comment by KronicDeth** [comment]
Transaction ``

```sh
curl --data '{"method":"eth_getTransactionByHash","params":["0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa"],"id":1,"jsonrpc":"2.0"}' \
  -H "Content-Type: application/json" \
  -X POST "https://sokol.poa.network"
```

```json
{
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x535d2c9461a8d78f7a4a70ea722d8a71500137b343807d161cc9999561b4f0b6",
    "blockNumber": "0x2d8a39",
    "chainId": null,
    "condition": null,
    "creates": null,
    "from": "0xbeaa34084ab851d545e69fe54bb251832424dfcb",
    "gas": "0x5208",
    "gasPrice": "0x3b9aca00",
    "hash": "0x03cd5899a63b6f6222afda8705d059fd5a7d126bcabe962fb654d9736e6bcafa",
    "input": "0x",
    "nonce": "0x1b19",
    "publicKey": "0x5647b597bb24fa6ec1c07fce8411782eff20370a94057d0cca3dffdb26f48273bf9d3e61b37054c9f8ed28706bb744025c0d6068d9b01ee35e127df159db4ac2",
    "r": "0xcaba7be8f8d6d870dd781ba0bceb4bb94aca0666019d28bf7aa926c968ec8882",
    "raw": "0xf86a821b19843b9aca0082520894e3354c04905a435e7238b89685b2c79368a5d8cb8504a817c800801ba0caba7be8f8d6d870dd781ba0bceb4bb94aca0666019d28bf7aa926c968ec8882a04e2b73788e45d55c3a15aa58528422bcca3b0c0048284691607f83339e885671",
    "s": "0x4e2b73788e45d55c3a15aa58528422bcca3b0c0048284691607f83339e885671",
    "standardV": "0x0",
    "to": "0xe3354c04905a435e7238b89685b2c79368a5d8cb",
    "transactionIndex": "0x1",
    "v": "0x1b",
    "value": "0x4a817c800"
  },
  "id": 1
}
```
