### ISSUE TITLE
ON CONFLICT DO UPDATE command cannot affect row a second time in insert_addresses

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/poa-explorer#309]
Reported original by @acravenho in Slack

### Steps to reproduce

> I just ran the indexer again and I seem to be getting this error repeatedly

### Expected behaviour

Duplicate addresses apply the same logic as the `ON CONFLICT` clauses no matter if they are duplicated in on batch or across batches.

### Actual behaviour

```
[error] Task #PID<0.741.0> started from Explorer.Indexer.AddressBalanceFetcher terminating
** (Postgrex.Error) ERROR 21000 (cardinality_violation): ON CONFLICT DO UPDATE command cannot affect row a second time
    (explorer) lib/explorer/repo.ex:54: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain.ex:2461: Explorer.Chain.insert_changes_list/2
    (explorer) lib/explorer/chain.ex:2295: Explorer.Chain.insert_addresses/2 
    (explorer) lib/explorer/indexer/address_balance_fetcher.ex:57: Explorer.Indexer.AddressBalanceFetcher.run/2
    (explorer) lib/explorer/buffered_task.ex:328: anonymous fn/3 in Explorer.BufferedTask.spawn_next_batch/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<3.48319259/0 in Explorer.BufferedTask.spawn_next_batch/1>
    Args: []
[error] Could not insert all of chunk into Elixir.Explorer.Chain.Address using options because of error.
```

<details>
```
Chunk:

[%{fetched_balance: #Explorer.Chain.Wei<0>, fetched_balance_block_number: 2972100, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<6, 63, 227, 186, 252, 249, 61, 9, 157, 215, 224, 155, 51, 114, 100, 29, 197, 224, 78, 21>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<0>, fetched_balance_block_number: 2971736, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<9, 103, 143, 66, 135, 252, 233, 90, 10, 112, 84, 100, 36, 12, 14, 142, 134, 198, 16, 193>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<136752582191071364421920>, fetched_balance_block_number: 2972100, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<9, 205, 168, 82, 121, 211, 206, 108, 64, 211, 36, 16, 129, 151, 97, 35, 114, 166, 209, 50>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<0>, fetched_balance_block_number: 2972100, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<11, 85, 253, 186, 158, 40, 140, 35, 207, 62, 176, 76, 111, 35, 125, 59, 208, 247, 81, 214>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<179877594435834582567793>, fetched_balance_block_number: 2972101, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<29, 138, 93, 178, 14, 11, 34, 230, 150, 251, 46, 188, 20, 63, 53, 54, 99, 62, 205, 156>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<0>, fetched_balance_block_number: 2972100, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<35, 70, 141, 183, 244, 184, 255, 73, 36, 176, 112, 154, 183, 174, 9, 113, 179, 188, 141, 40>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, 

.....
updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<999999062762000000000>, fetched_balance_block_number: 2971736, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<39, 101, 247, 247, 120, 63, 218, 72, 33, 240, 101, 138, 236, 176, 79, 119, 138, 22, 194, 182>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<5058306940274825000000>, fetched_balance_block_number: 2972100, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<53, 27, 254, 94, 167, 136, 237, 18, 89, 151, 26, 136, 37, 174, 178, 138, 117, 98, 253, 203>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<4999998316933000000000>, fetched_balance_block_number: 2971837, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<54, 212, 17, 62, 213, 7, 25, 246, 183, 234, 99, 116, 62, 112, 129, 25, 177, 10, 89, 119>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2018-06-19 16:44:57.353270Z>}, %{fetched_balance: #Explorer.Chain.Wei<1260159060000000000>, fetched_balance_block_number: 2971899, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<63, 244, 171, 210, 239, 193, 176, 206, 195, 225, 134, 16, 25, 15, 217, 131, 14, 211, fetched_balance_block_number: 2972100, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<83, 46, 6, 158, 32, 11, 227, 227, 114, 218, 150, 128, 135, 40, 38, 187, 8, 202, 239, 145>>}, inserted_at: #DateTime<2018-06-19 16:44:57.353270Z>, updated_at: #DateTime<2 (truncated)
```

</details>

**Comment by KronicDeth** [comment]
This behavior makes sense, as `InternalTransactionFetcher` and `AddressBalanceFetcher` are written the same way and `InternalTransactionFetcher` has the same problem in #289.

`AddressBalanceFetcher` producing duplicates is *more* expected though because multiple write paths may encounter the same address and at different `fetch_balance_block_numbers` as it is reused it is unexpected for `InternalTransactionFetcher` as we should only see a transaction hash once.

The same de-duping I'm doing for InternalTransactionFetcher can be done in AddressBalanceFetcher, it just doesn't need to be logged in AddressBalanceFetcher because it is expected and explainable
