### ISSUE TITLE
UndefinedFunctionError- function Explorer.Chain.Hash.Truncated.type/0 is undefined

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#391]
After the recent code changes, I tried starting the indexer after dropping the db and I received this error immediately while trying to start the application:

```
[error] Task #PID<0.548.0> started from Explorer.Chain.Statistics.Server terminating
** (UndefinedFunctionError) function Explorer.Chain.Hash.Truncated.type/0 is undefined (module Explorer.Chain.Hash.Truncated is not available)
    Explorer.Chain.Hash.Truncated.type()
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (explorer) lib/explorer/chain/statistics.ex:75: Explorer.Chain.Statistics.fetch/0
    (explorer) lib/explorer/chain/statistics/server.ex:33: anonymous fn/0 in Explorer.Chain.Statistics.Server.handle_info/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
Function: #Function<0.110801189/0 in Explorer.Chain.Statistics.Server.handle_info/2>
    Args: []
[error] Task #PID<0.575.0> started from Explorer.Chain.Statistics.Server terminating
** (UndefinedFunctionError) function Explorer.Chain.Hash.Truncated.type/0 is undefined (module Explorer.Chain.Hash.Truncated is not available)
    Explorer.Chain.Hash.Truncated.type()
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (explorer) lib/explorer/chain/statistics.ex:75: Explorer.Chain.Statistics.fetch/0
    (explorer) lib/explorer/chain/statistics/server.ex:33: anonymous fn/0 in Explorer.Chain.Statistics.Server.handle_info/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
Function: #Function<0.110801189/0 in Explorer.Chain.Statistics.Server.handle_info/2>
    Args: []
[error] Task #PID<0.577.0> started from Explorer.Chain.Statistics.Server terminating
** (UndefinedFunctionError) function Explorer.Chain.Hash.Truncated.type/0 is undefined (module Explorer.Chain.Hash.Truncated is not available)
    Explorer.Chain.Hash.Truncated.type()
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (explorer) lib/explorer/chain/statistics.ex:75: Explorer.Chain.Statistics.fetch/0
    (explorer) lib/explorer/chain/statistics/server.ex:33: anonymous fn/0 in Explorer.Chain.Statistics.Server.handle_info/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
Function: #Function<0.110801189/0 in Explorer.Chain.Statistics.Server.handle_info/2>
    Args: []
[error] Task #PID<0.583.0> started from Explorer.Chain.Statistics.Server terminating
** (UndefinedFunctionError) function Explorer.Chain.Hash.Truncated.type/0 is undefined (module Explorer.Chain.Hash.Truncated is not available)
    Explorer.Chain.Hash.Truncated.type()
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (explorer) lib/explorer/chain/statistics.ex:75: Explorer.Chain.Statistics.fetch/0
    (explorer) lib/explorer/chain/statistics/server.ex:33: anonymous fn/0 in Explorer.Chain.Statistics.Server.handle_info/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
Function: #Function<0.110801189/0 in Explorer.Chain.Statistics.Server.handle_info/2>
    Args: []
[info] Application explorer exited: shutdown
** (Mix) Could not start application explorer_web: {:not_running, :explorer}
```

### Steps to reproduce

1. Cloned repo
2. `cp apps/explorer/config/dev.secret.exs.example apps/explorer/config/dev.secret.exs`
3. `cp apps/explorer_web/config/dev.secret.exs.example apps/explorer_web/config/dev.secret.exs`
4. `mix do deps.get, local.rebar, deps.compile, compile`
5. `mix do ecto.drop, ecto.create, ecto.migrate`
6. `cd apps/explorer_web/assets && npm install; cd -`
7. ` cd apps/explorer && npm install; cd -`
8. `DEBUG_INDEXER=1 iex -S mix phx.server`

### Expected behaviour

I expected the explorer to start.

### Actual behaviour

I received the error above.

**Comment by tmecklem** [comment]
It looks like a collision between a couple of recent PRs. I guess Explorer.Chain.Hash.Truncated was removed but the changes in #382 still referenced it. I can take a look.
