### ISSUE TITLE
update or delete on table "blocks" violates foreign key constraint "transactions_block_hash_fkey" on table "transactions"

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/poa-explorer#415]
Indexer gets stuck with `update or delete on table "blocks" violates foreign key constraint "transactions_block_hash_fkey" on table "transactions"`

### Steps to reproduce

1. Run indexer against Sokol

### Expected behaviour

Error does not occur

### Actual behaviour

```
[error] Postgrex.Protocol (#PID<0.551.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1415.0> exited: an exception was raised:
    ** (Postgrex.Error) ERROR 23503 (foreign_key_violation): update or delete on table "blocks" violates foreign key constraint "transactions_block_hash_fkey" on table "transactions"

    table: transactions
    constraint: transactions_block_hash_fkey

Key (hash)=(\x58f0ac633ed66f9988ff69a8599cad0b8e37e7758637721d2280567987e64f65) is still referenced from table "transactions".
        (explorer) lib/explorer/repo.ex:53: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (explorer) lib/explorer/chain.ex:2472: Explorer.Chain.insert_changes_list/2
        (explorer) lib/explorer/chain.ex:2390: Explorer.Chain.insert_blocks/2
        (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
        (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
        (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
        (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
        (indexer) lib/indexer/block_fetcher.ex:203: Indexer.BlockFetcher.insert/3
        (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by KronicDeth** [comment]
The block with has 0x58f0ac633ed66f9988ff69a8599cad0b8e37e7758637721d2280567987e64f65has two transactions:

`curl --data '{"method":"eth_getBlockByHash","params":["0x58f0ac633ed66f9988ff69a8599cad0b8e37e7758637721d2280567987e64f65", true],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST "https://sokol.poa.network" | jq`

```json
{
  "jsonrpc": "2.0",
  "result": {
    "author": "0x4e20226355b4464cf8f3b67fc318b753a7c125b3",
    "difficulty": "0xfffffffffffffffffffffffffffffffe",
    "extraData": "0xd583010a068650617269747986312e32362e32826c69",
    "gasLimit": "0x7a1200",
    "gasUsed": "0xa410",
    "hash": "0x58f0ac633ed66f9988ff69a8599cad0b8e37e7758637721d2280567987e64f65",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "0x4e20226355b4464cf8f3b67fc318b753a7c125b3",
    "number": "0x360c21",
    "parentHash": "0xa183656449c600b28efaa2404d70f0b82625decaf7ed3656a81ad4c3cd043d9d",
    "receiptsRoot": "0xd95b673818fa493deec414e01e610d97ee287c9421c8eff4102b1647c1a184e4",
    "sealFields": [
      "0x8412429dfa",
      "0xb841f535933ed3220af81a0cb2299bc493e35e5ef4e96821feb7c5e9db62cbffd8246c8f3220b1e46d82c5896f7358e2916b61639957bb76e95a9b42da2b5b31292101"
    ],
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "signature": "f535933ed3220af81a0cb2299bc493e35e5ef4e96821feb7c5e9db62cbffd8246c8f3220b1e46d82c5896f7358e2916b61639957bb76e95a9b42da2b5b31292101",
    "size": "0x320",
    "stateRoot": "0x8f4e3a1fcf7d9fa9c3a830f7f575b92e9ed3095d1cd2c7339b4ab75325f60dd2",
    "step": "306355706",
    "timestamp": "0x5b4d15e2",
    "totalDifficulty": "0x360c20ffffffffffffffffffffffffed8955e5",
    "transactions": [
      {
        "blockHash": "0x58f0ac633ed66f9988ff69a8599cad0b8e37e7758637721d2280567987e64f65",
        "blockNumber": "0x360c21",
        "chainId": null,
        "condition": null,
        "creates": null,
        "from": "0xbeaa34084ab851d545e69fe54bb251832424dfcb",
        "gas": "0x5208",
        "gasPrice": "0x3b9aca00",
        "hash": "0x70e1798f6a72b91141aac7994fc8a357785e244f88fa0daf4a94f05fa27a3441",
        "input": "0x",
        "nonce": "0x7aa7",
        "publicKey": "0x5647b597bb24fa6ec1c07fce8411782eff20370a94057d0cca3dffdb26f48273bf9d3e61b37054c9f8ed28706bb744025c0d6068d9b01ee35e127df159db4ac2",
        "r": "0x79294f1604d38660a0e973984b0b58b4aa23cc61d2f047324a9376e179b4cf62",
        "raw": "0xf86a827aa7843b9aca0082520894beaa34084ab851d545e69fe54bb251832424dfcb8504a817c800801ba079294f1604d38660a0e973984b0b58b4aa23cc61d2f047324a9376e179b4cf62a0528696ebab6170cfd18b5daeda7d9f5696a6e47acb2e355d0eb9cb29c8806809",
        "s": "0x528696ebab6170cfd18b5daeda7d9f5696a6e47acb2e355d0eb9cb29c8806809",
        "standardV": "0x0",
        "to": "0xbeaa34084ab851d545e69fe54bb251832424dfcb",
        "transactionIndex": "0x0",
        "v": "0x1b",
        "value": "0x4a817c800"
      },
      {
        "blockHash": "0x58f0ac633ed66f9988ff69a8599cad0b8e37e7758637721d2280567987e64f65",
        "blockNumber": "0x360c21",
        "chainId": "0x4d",
        "condition": null,
        "creates": null,
        "from": "0xc45e4830dff873cf8b70de2b194d0ddd06ef651e",
        "gas": "0xe57e0",
        "gasPrice": "0x3b9aca00",
        "hash": "0xd207af22ddf853e9c137f131c0c51315bc3ecf3208bdfeae0d0062c4693b121c",
        "input": "0x",
        "nonce": "0x17d3",
        "publicKey": "0x568d8093c01643bc923d209e30f41813fb817be8716d1a1d9660c2e661ea174f2b3dd9f597180568a1cacc6bd47993c622f7a3270b5ec4cf9b93f6123a6f4ac8",
        "r": "0x90080e63fa03ef276fe88b4497eb77ca89c2c38615b4ee1539a48782be734ba8",
        "raw": "0xf86c8217d3843b9aca00830e57e0942081e5c4d4cc73100ca6d5007fddcdda424953d48504a817c8008081bea090080e63fa03ef276fe88b4497eb77ca89c2c38615b4ee1539a48782be734ba8a03ff7184ebf2c7bb53eba9d988f2e9c806a2d181bca873a6c64221d22788d6fb2",
        "s": "0x3ff7184ebf2c7bb53eba9d988f2e9c806a2d181bca873a6c64221d22788d6fb2",
        "standardV": "0x1",
        "to": "0x2081e5c4d4cc73100ca6d5007fddcdda424953d4",
        "transactionIndex": "0x1",
        "v": "0xbe",
        "value": "0x4a817c800"
      }
    ],
    "transactionsRoot": "0xecc1a5249ed342877d6bd5b8efa36a6c577eeb3f1f0e18e283a01a87c8ab96b3",
    "uncles": []
  },
  "id": 1
}
```

It is number `3542049`, so near head of the chain.

Looking at the database, the transactions that have that block as their parent are

1. `cd apps/explorer`
2. `iex -S mix`
3. `{:ok, block} = Explorer.Chain.number_to_block(3542049)`
4. `Explorer.Chain.block_to_transactions(block) |> Enum.map(fn %{hash: hash} -> to_string(hash) end)`
    ```elixir
    ["0xd207af22ddf853e9c137f131c0c51315bc3ecf3208bdfeae0d0062c4693b121c",
     "0x70e1798f6a72b91141aac7994fc8a357785e244f88fa0daf4a94f05fa27a3441"]
    ```

Those hashes match the hashes transaction hashes from the `curl` request, so the database appears to match the chain.  Some other field must be causes the error on update as there should be no block deletes.
