### ISSUE TITLE
Deployment- Error when trying to verify a smart contract

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#442]
I'm receiving the following error when attempting to verify a smart contract:

```
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: 14:01:21.249 request_id=gujis2lcqv0ol5bf6gcdk64uq5vohe1u [info] Sent 500 in 7ms
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: 14:01:21.251 [error] #PID<0.8411.4> running ExplorerWeb.Endpoint terminated
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: Server: sokg-explorer-sokol-elb-682326660.us-east-1.elb.amazonaws.com:80 (http)
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: Request: POST /en/addresses/0x8974cd6822ff825ea9e47bef6416cbf73fd328b6/contract_verifications
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: ** (exit) an exception was raised:
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: ** (ErlangError) Erlang error: :enoent
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (elixir) lib/system.ex:622: System.cmd("node", ["/opt/app/_build/prod/lib/explorer/priv/compile_solc.js", "contract SimpleStorage {\r\n    uint storedData;\r\n\r\n    function set(uint x) public {\r\n        storedData = x;\r\n    }\r\n\r\n    function get() public constant returns (uint) {\r\n        return storedData;\r\n    }\r\n}", "v0.4.24+commit.e67f0147", "0"], [])
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer) lib/explorer/smart_contract/solidity/code_compiler.ex:64: Explorer.SmartContract.Solidity.CodeCompiler.run/4
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer) lib/explorer/smart_contract/verifier.ex:24: Explorer.SmartContract.Verifier.evaluate_authenticity/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer) lib/explorer/smart_contract/publisher.ex:27: Explorer.SmartContract.Publisher.publish/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer_web) lib/explorer_web/controllers/address_contract_verification_controller.ex:24: ExplorerWeb.AddressContractVerificationController.create/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer_web) lib/explorer_web/controllers/address_contract_verification_controller.ex:1: ExplorerWeb.AddressContractVerificationController.action/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer_web) lib/explorer_web/controllers/address_contract_verification_controller.ex:1: ExplorerWeb.AddressContractVerificationController.phoenix_controller_pipeline/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer_web) lib/explorer_web/endpoint.ex:1: ExplorerWeb.Endpoint.instrument/4
```

The file `/opt/app/_build/prod/lib/explorer/priv/compile_solc.js` exists but requires `solc-js`, I'm assuming this is where the problem is. 

### Environment

* Operating System: CentOS Linux

### Steps to reproduce

1. Use the [poa-explorer-infra](https://github.com/poanetwork/poa-explorer-infra) repo to deploy infrastructure on AWS
2. Upload explorer to the s3 bucket
3. Use CodeDeploy to launch an instance
4. Try and verify a smart contract

### Expected behaviour

When submitting the form I should receive an error that the bytecode doesn't match or be redirected to the successfully state.

### Actual behaviour

Internal Server Error

**Comment by amandasposito** [comment]
```

**Comment by amandasposito** [comment]
It seems to be a problem with the `node` that is not installed in the server.

```
[ec2-user@ip-10-0-0-245 explorer]$ node --v
-bash: node: command not found
```

```
[ec2-user@ip-10-0-0-245 explorer]$ iex -S mix
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.6.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> System.find_executable("node")
nil
```

There are two ways of fixing this: 

1. Install the `node` globally in the machine;
2. Distribute it in priv and keep the executables on the project repository.

**Comment by amandasposito** [comment]
Resolved with https://github.com/poanetwork/poa-explorer/pull/456 and https://github.com/poanetwork/poa-explorer-infra/pull/42
