### ISSUE TITLE
Can this explorer be used on a private geth blockchain for a different blockchain than the POA mainnet??

### ISSUE THREAD

**Issue by alexacostarua** [poanetwork/poa-explorer#504]
I've got this explorer to work.  I've attempted setting environment variables in the .bashrc to make it function with a private blockchain but had no luck.  Is there a way to make this work with a private blockchain on geth with a completely different chain id aswell??

**Comment by crossoveranx** [comment]
Does support for private parity blockchains exist? If so, please direct me to the appropriate information where I can modify the chain variables - I could not find the relevant info.

**Comment by alexacostarua** [comment]
@crossoveranx @KronicDeth Yes I have moved onto parity as well for my private blockchain and am also wondering the same-thing.  Editing the .bashrc does nothing for adding a custom endpoint.  Even if there no config for a custom one where would the mainnet config be?

**Comment by KronicDeth** [comment]
@crossoveranx edit the URLs in the configs from pointing at sokol to JSONRPC endpoints on the nodes in your chain:

https://github.com/poanetwork/poa-explorer/blob/6983671a02201997bdac06775db7754a96ff06b0/apps/indexer/config/dev/parity.exs#L9-L13

https://github.com/poanetwork/poa-explorer/blob/6983671a02201997bdac06775db7754a96ff06b0/apps/indexer/config/prod/parity.exs#L9-L12

If you're not just running it locally for your, but want it hosted on AWS and reskinned, so that it doesn't say "POA" for the "Ether" unit, we can cover that too.

**Comment by KronicDeth** [comment]
@alexacostarua there is no `.bashrc` in this repo.  What are you referring to?

**Comment by alexacostarua** [comment]
https://github.com/poanetwork/poa-explorer/issues/498 @KronicDeth Maybe I phrased the question wrong at the time.

**Comment by crossoveranx** [comment]
@KronicDeth Can you provide insight into the file modifications for the "PoA" and "Ether" unit changes?

**Comment by KronicDeth** [comment]
POA as the unit of Ether is set here:

https://github.com/poanetwork/blockscout/blob/3cd70c2152316d9334929a3bb897f12a11e0d7cd/apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po#L302-L311

Change POA to Ether to get the translation back to normal "Ether".

**Comment by KronicDeth** [comment]
@crossoveranx it looks like your node is reporting a `"status"`, but with `null` for the value (in JSON), which is translated to `nil` in Elixir:

https://github.com/poanetwork/blockscout/blob/5e8ac9fb49bc9ddcd11983fd6bc90e6be603c6cb/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex#L293-L301

We haven't encountered that before.

1. What variant of node are you connecting to?  Geth, Parity, other?
2. What is the version of that node software?
3. Is this a pre-Byzantium block?

**Comment by crossoveranx** [comment]
1. Connecting to Parity
2. version Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
3. No.

I will continue looking into it as well, but please let me know if you'd like anymore info.

**Comment by acravenho** [comment]
Hi @crossoveranx,

Please update your node to the latest stable version of Parity which is `1.11.8`. That should fix your issue.

**Comment by crossoveranx** [comment]
@acravenho 

Thank you, this fixed my issue.

**Comment by crossoveranx** [comment]
@acravenho 
Perhaps I spoke too soon. It works until I submit a transaction for creating a smart contract and then I receive another flurry of errors. 

Here's a sample: 

```

** (CaseClauseError) no case clause matching: nil
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:295: EthereumJSONRPC.Receipt.entry_to_elixir/1
    (elixir) lib/map.ex:203: Map.new_transform/3
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:139: EthereumJSONRPC.Receipts.fetch/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.19830.1>, {{:case_clause, nil}, [{EthereumJSONRPC.Receipt, :entry_to_elixir, 1, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 295]}, {Map, :new_transform, 3, [file: 'lib/map.ex', line: 203]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1294]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 139]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 88]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
16:59:46.199 [error] Task #PID<0.19841.1> started from #PID<0.19839.1> terminating
** (CaseClauseError) no case clause matching: nil
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:295: EthereumJSONRPC.Receipt.entry_to_elixir/1
    (elixir) lib/map.ex:203: Map.new_transform/3
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:139: EthereumJSONRPC.Receipts.fetch/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<1.94702972/1 in Indexer.BlockFetcher.Receipts.fetch/2>, [[%{block_hash: "0x6cffc5a855743a660c64659d1d1f8c752fb35ad4d99b1030975ec0259024cd68", block_number: 2, from_address_hash: "0x78d4e346976db769e316f69578b996f64a50e91a", gas: 4500000, gas_price: 1000000000, hash: "0xed79d648243a362a91fd3c89d390beaeb1949545fdb5c3b1439d08269dd4c745", index: 0, input: "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506102f8806100606000396000f300608060405260043610610062576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630900f01014610067578063445df0ac146100aa5780638da5cb5b146100d5578063fdacd5761461012c575b600080fd5b34801561007357600080fd5b506100a8600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610159565b005b3480156100b657600080fd5b506100bf610241565b6040518082815260200191505060405180910390f35b3480156100e157600080fd5b506100ea610247565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561013857600080fd5b506101576004803603810190808035906020019092919050505061026c565b005b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561023d578190508073ffffffffffffffffffffffffffffffffffffffff1663fdacd5766001546040518263ffffffff167c010000000000000000000000000000000000000000000000000000000002815260040180828152602001915050600060405180830381600087803b15801561022457600080fd5b505af1158015610238573d6000803e3d6000fd5b505050505b5050565b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614156102c957806001819055505b505600a165627a7a7230582097a9f231e4d31e3775dcd0f1494657e68823ef0f637036ae1186a546346940cb0029", nonce: 0, r: 54361910062585831258171249089091351970015397865297362545157863153917250560512, s: 29898549158883223746235779205296819605614664414054824904335074243177980272618, to_address_hash: nil, v: 18025, value: 0}, %{block_hash: "0x9348f91aa6380c5994f669635be0978bb5b49c8037d33679c7f703ac4d8a4ec6", block_number: 3, from_address_hash: "0x78d4e346976db769e316f69578b996f64a50e91a", gas: 4500000, gas_price: 1000000000, hash: "0x6a3bef2aae736b6102bc256ee63e883d354a4cd43d53cc806e51618a85f29d52", index: 0, input: "0xfdacd5760000000000000000000000000000000000000000000000000000000000000001", nonce: 1, r: 78362422827534491648114101640892268419999188881441000677737770636793745822852, s: 29223099819748515112991702344724132941149711814310885935325918894713400154931, to_address_hash: "0xebb6b20fdc49f68142471709923cc4ee33974e6f", v: 18026, value: 0}, %{block_hash: "0xab75a03a674150a4d648993cc72e432e5b07e7b468122e5d46d73d578c269a83", block_number: 4, from_address_hash: "0x78d4e346976db769e316f69578b996f64a50e91a", gas: 4500000, gas_price: 1000000000, hash: "0x6104255f4d5e2b6922792507379e213b14ff53b9131a7789613b65385d37815e", index: 0, input: "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550613168806100606000396000f300608060405260043610610203576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168062a35aa214610208578063025ec81a14610239578063043106c0146102865780630489fa70146102b75780630bd85158146102f25780630c55d92514610330578063124f24181461036157806325cf512d1461039257806326df61f6146103d15780633138ee5c146103fc5780633562fd20146104685780633836fe6e146104a357806344bfa56e146104e65780634c77e5ba14610590578063506d7d001461060157806352d2d83d146106535780635a2bf25a146106905780636aebbbd9146106e15780636d38156f1461071c57806373fb35ee146107965780637a0e03ec146108035780638267a9ee1461084e57806382914e5d1461087f57806383197ef01461099357806384d7c99d146109aa5780638da5cb5b146109db5780638ffa969014610a325780639007127b14610a7b57806393fe424814610ac05780639420e58d14610af1578063a209a29c14610b4c578063a77aa49e14610bf6578063a98ad19914610c31578063ba69fcaa14610c74578063bdc963d814610ca5578063c8d1c01714610cea578063c9a52d2c14610d25578063dc02511e14610d6e578063f2fde38b14610da9578063f5074f4114610dec578063f586606614610e2f578063ffbd400b14610e78575b600080fd5b34801561021457600080fd5b506102376004803603810190808035600019169060200190929190505050610ebb565b005b34801561024557600080fd5b506102686004803603810190808035600019169060200190929190505050610f98565b60405180826000191660001916815260200191505060405180910390f35b34801561029257600080fd5b506102b56004803603810190808035600019169060200190929190505050610fbd565b005b3480156102c357600080fd5b506102f06004803603810190808035906020019082018035906020019190919293919293905050506110ad565b005b3480156102fe57600080fd5b5061032e6004803603810190808035600019169060200190929190803560ff1690602001909291905050506111ae565b005b34801561033c57600080fd5b5061035f6004803603810190808035600019169060200190929190505050611295565b005b34801561036d57600080fd5b50610390600480360381019080803560001916906020019092919050505061136e565b005b34801561039e57600080fd5b506103cf6004803603810190808035600019169060200190929190803560001916906020019092919050505061143f565b005b3480156103dd57600080fd5b506103e6611516565b6040518082815260200191505060405180910390f35b34801561040857600080fd5b506104116115d3565b6040518080602001828103825283818151815260200191508051906020019060200280838360005b83811015610454578082015181840152602081019050610439565b505050509050019250505060405180910390f35b34801561047457600080fd5b506104a1600480360381019080803560001916906020019092919080359060200190929190505050611746565b005b3480156104af57600080fd5b506104e4600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611819565b005b3480156104f257600080fd5b506105156004803603810190808035600019169060200190929190505050611935565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561055557808201518184015260208101905061053a565b50505050905090810190601f1680156105825780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34801561059c57600080fd5b506105bf60048036038101908080356000191690602001909291905050506119f2565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561060d57600080fd5b5061063d6004803603810190808035600019169060200190929190803560ff169060200190929190505050611a37565b6040518082815260200191505060405180910390f35b34801561065f57600080fd5b5061068e6004803603810190808035600019169060200190929190803515159060200190929190505050611afc565b005b34801561069c57600080fd5b506106df6004803603810190808035600019169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611be2565b005b3480156106ed57600080fd5b5061071a600480360381019080803560001916906020019092919080359060200190929190505050611cef565b005b34801561072857600080fd5b5061078060048036038101908080359060200190820180359060200190808060200260200160405190810160405280939291908181526020018383602002808284378201915050505050509192919290505050611de6565b6040518082815260200191505060405180910390f35b3480156107a25760" <> ..., nonce: 2, r: 107581055878105878145968707331221821199840833327106962398076375322476877056600, s: 2474420509961930345 (truncated)
16:59:46.204 [error] GenServer #PID<0.19837.1> terminating
** (CaseClauseError) no case clause matching: nil
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:295: EthereumJSONRPC.Receipt.entry_to_elixir/1
    (elixir) lib/map.ex:203: Map.new_transform/3
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:139: EthereumJSONRPC.Receipts.fetch/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.19836.1>, {{:case_clause, nil}, [{EthereumJSONRPC.Receipt, :entry_to_elixir, 1, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 295]}, {Map, :new_transform, 3, [file: 'lib/map.ex', line: 203]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1294]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 139]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 88]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
16:59:46.205 [error] Catchup index stream exited with reason ({{:case_clause, nil}, [{EthereumJSONRPC.Receipt, :entry_to_elixir, 1, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 295]}, {Map, :new_transform, 3, [file: 'lib/map.ex', line: 203]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1294]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 139]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 88]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restartin
```

**Comment by acravenho** [comment]
@crossoveranx  I just want to confirm that you have tracing enabled and you're fully synced. I've seen these types of errors when either of the these two weren't true. 

I'm spinning up a fresh Kovan node now to test against. It will take a little while to sync and will let you know the status soon.

**Comment by KronicDeth** [comment]
@acravenho 
> (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:295

is the same as in https://github.com/poanetwork/blockscout/issues/504#issuecomment-414656695, where for some reason the `"status"` key is being sent, but a `null` value for it.

**Comment by crossoveranx** [comment]
@acravenho 

I can confirm that I have tracing enabled. Additionally, the parity instance is fully synced - I am starting a fresh blockchain on a private network so the syncing is minimal.

**Comment by crossoveranx** [comment]
Btw, this issue has been resolved in the latest build for me.
